packages:
  - core
  - apps/*
  - packages/*

catalog:
  typescript: 5.8.3
  solid-js: 1.9.7
  '@solidjs/start': ^1.1.6
  '@solidjs/router': ^0.15.3
  '@solidjs/meta': ^0.29.4
  '@solidjs/testing-library': ^0.8.10
  vinxi: ^0.5.8
  zod: 4.0.5
  tailwindcss: 4.1.11
  tw-animate-css: 1.3.5
  class-variance-authority: ^0.7.1
  unplugin-icons: 22.1.0
  '@dotenvx/dotenvx': ^1.47.3
  '@kobalte/core': ^0.13.10
  '@kobalte/tailwindcss': 0.9.0
  cloudflare: ^4.4.1
  remult: 3.0.6
  better-auth: 1.2.12
  lodash-es: ^4.17.21
  vite: ^7.0.4
  vite-plugin-doctest: ^1.1.1
  vite-plugin-solid: 2.11.7
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
