packages:
  - fastcore
  - package-apps/*
  - package-libs/*

catalog:
  typescript: "^5.8.3"
  solid-js: "^1.9.7"
  "@solidjs/start": "^1.1.4"
  "@solidjs/router": "^0.15.3"
  "@solidjs/meta": "^0.29.4"
  "@solidjs/testing-library": "^0.8.10"
  vinxi: "^0.5.7"
  zod: "^3.25.67"
  tailwindcss: "^4.1.7"
  tw-animate-css: "^1.3.4"
  class-variance-authority: "^0.7.1"
  unplugin-icons: "^22.1.0"
  "@dotenvx/dotenvx": "^1.44.2"
  "@kobalte/core": "^0.13.9"
  "@kobalte/tailwindcss": "^0.9.0"
  cloudflare: "^4.4.1"
  remult: "^3.0.5"
  better-auth: "^1.2.9"