packages:
  - core
  - apps/*
  - packages/*

catalog:
  '@dotenvx/dotenvx': ^1.49.0
  '@kobalte/core': 0.13.11
  '@kobalte/tailwindcss': 0.9.0
  '@solidjs/meta': ^0.29.4
  '@solidjs/router': ^0.15.3
  '@solidjs/start': ^1.1.7
  '@solidjs/testing-library': ^0.8.10
  better-auth: 1.3.8
  class-variance-authority: 0.7.1
  cloudflare: ^5.0.0
  lodash-es: ^4.17.21
  remult: 3.2.1
  solid-js: 1.9.9
  tailwindcss: 4.1.12
  tw-animate-css: 1.3.8
  typescript: 5.9.2
  unplugin-icons: 22.2.0
  vinxi: ^0.5.8
  vite: ^7.1.4
  vite-plugin-doctest: ^1.1.1
  vite-plugin-solid: 2.11.8
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  zod: 4.1.5
