packages:
  - database
  - remult-core
  - plibs/*
  - pcore/*
  - papps/*

catalog:
  typescript: "^5.8.3"
  solid-js: "^1.9.7"
  "@solidjs/router": "^0.15.3"
  "@solidjs/testing-library": "^0.8.10"
  zod: "^3.25.23"
  tailwindcss: "^4.1.7"
  tw-animate-css: "^1.3.0"
  class-variance-authority: "^0.7.1"
  unplugin-icons: "^22.1.0"
  "@dotenvx/dotenvx": "^1.44.1"
  "@kobalte/core": "^0.13.9"
  "@kobalte/tailwindcss": "^0.9.0"
  "cloudflare": "^4.3.0"
  "remult": "^3.0.4"
  "better-auth": "^1.2.8"
