"$schema" = "node_modules/wrangler/config-schema.json"
name = "tanstart-demo"
main = ".output/server/index.mjs"
compatibility_date = "2025-08-25"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

[env]
production = {}
